resize_shape: [256, 256]
targets: ['Fire_Images']
model_file_paths: ["cnn_classifier_layers.json", "cnn_classifier_params.h5"]
base_model_url: "https://github.com/Jetpuffed/Fire-Detection-API/releases/download/v1.0.0"
model_sha256: "14d85113aaaa1c42061f8d04cdfc2559f61c53f9"